---
  # Tasks to install Tomcat8.
  # Written by Madison Flannery.

  - name: "Create Tomcat8 group"
    group: name=tomcat8 state=present
    become: yes

  - name: "Create Tomcat8 user"
    user: name=tomcat8 shell=/bin/false groups=tomcat8 home=/opt/tomcat8
    become: yes

  - name: "Download Tomcat8"
    get_url:
      url: http://archive.apache.org/dist/tomcat/tomcat-8/v8.5.6/bin/apache-tomcat-8.5.6.tar.gz
      dest: /opt/apache-tomcat-8.5.6.tar.gz
      checksum: md5:E273E27DEB1828AE5F19374616B9FBA8
    become: yes

  - name: "Unarchive the downloaded Tomcat8"
    unarchive: src=/opt/apache-tomcat-8.5.6.tar.gz dest=/opt/tomcat8 remote_src=yes

  # Move file contents and remove lower level folder
  - name: "Clean up Tomcat8 directory structure"
    command: "mv /opt/apache-tomcat-8.5.6/ /opt/tomcat8/"
    become: yes

  - name: "Chown the Tomcat8 directory"
    file: dest=/opt/apache-tomcat-8.5.6/ owner=tomcat8 group=tomcat8 recurse=yes

  - name: "Create intlctl/upstart script"
    template: src=tomcat.conf.j2 dest=/etc/init/tomcat.conf
    become: yes
    become_user: root

  - name: "Reload tomcat8 initctl config"
    service: name=tomcat8 state=reloaded
    become: yes
    become_user: root
