---
  # Tasks to install Tomcat8.
  # Written by Madison Flannery.

  - name: "Create Tomcat8 group"
    group: name=tomcat8 state=present
    become: yes

  - name: "Create Tomcat8 user"
    user: name=tomcat8 shell=/bin/false groups=tomcat8 home="{{ tomcat_home }}"
    become: yes

  - name: "Download Tomcat8"
    get_url:
      url: http://archive.apache.org/dist/tomcat/tomcat-8/v8.5.6/bin/apache-tomcat-8.5.6.tar.gz
      dest: /opt/apache-tomcat-8.5.6.tar.gz
      checksum: md5:E273E27DEB1828AE5F19374616B9FBA8
    become: yes

  - name: "Unarchive the downloaded Tomcat8"
    unarchive: src=/opt/apache-tomcat-8.5.6.tar.gz dest=/opt/ remote_src=yes

  # Move file contents and remove lower level folder
  # Rename unarchived folder to tomcat8.
  # We first need to delete existing to avoid errors.
  - name: "Remove originally created directory"
    file: path="{{ tomcat_home }}" state=absent

  - name: "Clean up Tomcat8 directory structure"
    command: "mv /opt/apache-tomcat-8.5.6 {{ tomcat_home }}"
    become: yes

  - name: "Chown the Tomcat8 directory"
    file: dest="{{ tomcat_home }}" owner=tomcat8 group=tomcat8 recurse=yes

  # Create initctl script and reload initctl config.
  - name: "Create initctl script"
    template: src=tomcat8.conf.j2 dest=/etc/init/tomcat8.conf
    become: yes
    become_user: root

  - name: "Reload tomcat8 initctl config"
    command: "initctl reload-configuration"
    become: yes
    become_user: root
