---
  # Tasks to install Tomcat8.
  # Written by Madison Flannery.

  - name: "Create Tomcat8 group"
    group: name=tomcat8 state=present
    become: yes

  - name: "Create Tomcat8 user"
    user: name=tomcat8 shell=/bin/false groups=tomcat8 home=/opt/tomcat8
    become: yes

  - name: download file with check (md5)
    get_url:
      url: http://archive.apache.org/dist/tomcat/tomcat-8/v8.5.6/bin/apache-tomcat-8.5.6.tar.gz
      dest: /opt/apache-tomcat-8.5.6.tar.gz
      checksum: md5:E273E27DEB1828AE5F19374616B9FBA8
    become: yes

#  - name: "Create Tomcat8 directory"

- unarchive: src=/opt/apache-tomcat-8.5.6.tar.gz dest=/usr/local/bin remote_src=yes
